[pytest]
pythonpath = .
addopts = 
    -n auto 
    -v
    --html=reports/execution_report.html
    --self-contained-html
    --screenshot=only-on-failure
    --video=retain-on-failure
    --tracing=retain-on-failure